version: '3.7'
services:
  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_KRAFT_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_KRAFT_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092
    volumes:
      - ./data/kafka1:/var/lib/kafka/data

  kafka2:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9093:9092"
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_KRAFT_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_KRAFT_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092
    volumes:
      - ./data/kafka2:/var/lib/kafka/data

  kafka3:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9094:9092"
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_KRAFT_BROKER_ID=3
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_KRAFT_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092
    volumes:
      - ./data/kafka3:/var/lib/kafka/data
